import { readFileSync } from "node:fs";
import supabase from "../web/lib/supabase.js";


// The watchlist, seeded once.
//
// Every entry was verified live before it landed here: each token was probed
// against its ATS and returned a real board with postings. Companies that hire
// through Workday or a bespoke careers site (Disney, NBCUniversal, Netflix,
// EA, Nike, Publicis, Dentsu, Havas, Edelman) have no public JSON endpoint and
// are deliberately absent rather than silently broken — better an honest gap
// than a source that reports zero forever.
//
// Weighted toward media and agencies on purpose: that is where the owner expects
// this particular summer to land, whatever the longer-term aim.
//
//   node scripts/seed-jobs.mjs
//
// Idempotent: re-running adds new rows and leaves existing ones alone.

const WATCHLIST = [

  // Round five: matched against the resume rather than the ambition.
  //
  // The first four rounds were weighted to PRODUCT MANAGEMENT, which is the
  // long-term aim. The resume sells something else: video production, agency
  // client work, social and brand, an e-commerce storefront run end to end,
  // and AI fluency. So this round is production and post houses, sports
  // organisations, advertising agencies weighted to Chicago, DTC brands,
  // entertainment and streaming, and marketing teams at technology companies.
  //
  // Every one was called, then re-checked by a second reader that had not seen
  // the first one's answer. 370 survived that; 11 were rejected at re-check and
  // 432 more had no endpoint anyone could confirm. A board that returns nothing
  // reports nothing forever, which is the whole reason for the second pass.
  { company: "Academy Sports", ats: "phenom", token: "careers.academy.com", category: "brand" },
  { company: "Alo Yoga", ats: "greenhouse", token: "aloyoga", category: "brand" },
  { company: "Banza", ats: "greenhouse", token: "banza", category: "brand" },
  { company: "BARK", ats: "greenhouse", token: "bark", category: "brand" },
  { company: "Blueland", ats: "lever", token: "blueland", category: "brand" },
  { company: "Bobbie", ats: "greenhouse", token: "bobbie", category: "brand" },
  { company: "Brilliant Earth", ats: "greenhouse", token: "brilliantearth", category: "brand" },
  { company: "Brooklinen", ats: "ashby", token: "brooklinen", category: "brand" },
  { company: "Bubble Skincare", ats: "greenhouse", token: "bubbleskincare", category: "brand" },
  { company: "Buck Mason", ats: "lever", token: "buckmason", category: "brand" },
  { company: "Deckers", ats: "workday", token: "deckers/wd5/Deckers", category: "brand" },
  { company: "Dicks Sporting Goods", ats: "workday", token: "dickssportinggoods/wd1/dsg", category: "brand" },
  { company: "Dollar Shave Club", ats: "greenhouse", token: "dollarshaveclub", category: "brand" },
  { company: "Eight Sleep", ats: "ashby", token: "eightsleep", category: "brand" },
  { company: "Everlane", ats: "greenhouse", token: "everlane", category: "brand" },
  { company: "Faherty Brand", ats: "greenhouse", token: "fahertybrand", category: "brand" },
  { company: "Fanatics Collectibles", ats: "greenhouse", token: "fanaticscollectibles", category: "brand" },
  { company: "GOAT Group", ats: "greenhouse", token: "goatgroup", category: "brand" },
  { company: "Gopuff", ats: "lever", token: "gopuff", category: "brand" },
  { company: "Grove Collaborative", ats: "greenhouse", token: "grovecollaborative", category: "brand" },
  { company: "Gymshark", ats: "greenhouse", token: "gymshark", category: "brand" },
  { company: "Harry's", ats: "greenhouse", token: "harrys", category: "brand" },
  { company: "HelloFresh", ats: "greenhouse", token: "hellofresh", category: "brand" },
  { company: "Hill House Home", ats: "greenhouse", token: "hillhousehome", category: "brand" },
  { company: "Hungryroot", ats: "greenhouse", token: "hungryroot", category: "brand" },
  { company: "LEGO Group", ats: "workday", token: "lego/wd103/LEGO_External", category: "brand" },
  { company: "Liquid I.V.", ats: "greenhouse", token: "liquidiv", category: "brand" },
  { company: "Little Spoon", ats: "greenhouse", token: "littlespoon", category: "brand" },
  { company: "Logitech", ats: "workday", token: "logitech/wd5/Logitech", category: "brand" },
  { company: "Mejuri", ats: "greenhouse", token: "mejuri", category: "brand" },
  { company: "Mercari", ats: "greenhouse", token: "mercari", category: "brand" },
  { company: "Misfits Market", ats: "greenhouse", token: "misfitsmarket", category: "brand" },
  { company: "Nanit", ats: "greenhouse", token: "nanit", category: "brand" },
  { company: "Nothing", ats: "greenhouse", token: "nothing", category: "brand" },
  { company: "OLLY", ats: "greenhouse", token: "olly", category: "brand" },
  { company: "Oura", ats: "greenhouse", token: "oura", category: "brand" },
  { company: "Parachute Home", ats: "greenhouse", token: "parachutehome", category: "brand" },
  { company: "Peak Design", ats: "greenhouse", token: "peakdesign", category: "brand" },
  { company: "PVH", ats: "workday", token: "pvh/wd1/PVH_Careers", category: "brand" },
  { company: "Quince", ats: "greenhouse", token: "quince", category: "brand" },
  { company: "Reformation", ats: "greenhouse", token: "reformation", category: "brand" },
  { company: "Rent the Runway", ats: "greenhouse", token: "renttherunway", category: "brand" },
  { company: "Rover", ats: "lever", token: "rover", category: "brand" },
  { company: "Ruggable", ats: "greenhouse", token: "ruggable", category: "brand" },
  { company: "Saatva", ats: "greenhouse", token: "saatva", category: "brand" },
  { company: "Seed", ats: "greenhouse", token: "seed", category: "brand" },
  { company: "SHEIN", ats: "greenhouse", token: "shein", category: "brand" },
  { company: "SimpliSafe", ats: "greenhouse", token: "simplisafe", category: "brand" },
  { company: "Sonos", ats: "workday", token: "sonos/wd1/Sonos", category: "brand" },
  { company: "Spot & Tango", ats: "greenhouse", token: "spotandtango", category: "brand" },
  { company: "Stitch Fix", ats: "greenhouse", token: "stitchfix", category: "brand" },
  { company: "StockX", ats: "greenhouse", token: "stockx", category: "brand" },
  { company: "Supergoop", ats: "greenhouse", token: "supergoop", category: "brand" },
  { company: "Tecovas", ats: "greenhouse", token: "tecovas", category: "brand" },
  { company: "The Farmer's Dog", ats: "greenhouse", token: "thefarmersdog", category: "brand" },
  { company: "Thrive Market", ats: "greenhouse", token: "thrivemarket", category: "brand" },
  { company: "Topgolf", ats: "workday", token: "topgolf/wd501/TopgolfCareers", category: "brand" },
  { company: "TULA Skincare", ats: "greenhouse", token: "tula", category: "brand" },
  { company: "Van Leeuwen", ats: "greenhouse", token: "vanleeuwenicecream", category: "brand" },
  { company: "VF Corporation", ats: "workday", token: "vfc/wd5/vfc_careers", category: "brand" },
  { company: "Whoop", ats: "ashby", token: "whoop", category: "brand" },
  { company: "YETI", ats: "workday", token: "yeticoolers/wd5/YETI", category: "brand" },
  { company: "Flexport", ats: "greenhouse", token: "flexport", category: "business" },
  { company: "Gartner", ats: "workday", token: "gartner/wd5/EXT", category: "business" },
  { company: "Basis Technologies", ats: "lever", token: "basis", category: "local" },
  { company: "Bounteous", ats: "lever", token: "bounteous", category: "local" },
  { company: "Chicago Cubs", ats: "workday", token: "my1060wd/wd5/Chicago_Cubs_FO", category: "local" },
  { company: "Claire's", ats: "workday", token: "claires/wd12/Claires", category: "local" },
  { company: "Home Chef", ats: "greenhouse", token: "homechef", category: "local" },
  { company: "Rush Street Interactive", ats: "greenhouse", token: "rushstreetinteractive", category: "local" },
  { company: "2K", ats: "greenhouse", token: "2k", category: "media" },
  { company: "5W Public Relations", ats: "greenhouse", token: "5wpr", category: "media" },
  { company: "Activision Blizzard", ats: "phenom", token: "careers.activision.com", category: "media" },
  { company: "Acxiom", ats: "workday", token: "acxiomllc/wd5/AcxiomUSA", category: "media" },
  { company: "Advanced Systems Group", ats: "ashby", token: "advanced-systems-group", category: "media" },
  { company: "AKQA", ats: "greenhouse", token: "akqa", category: "media" },
  { company: "AMC Networks", ats: "workday", token: "amcn/wd5/amcnetworks", category: "media" },
  { company: "AppLovin", ats: "greenhouse", token: "applovin", category: "media" },
  { company: "ASM Global", ats: "workday", token: "asmglobal/wd1/careers", category: "media" },
  { company: "BarkleyOKRP", ats: "greenhouse", token: "barkleyokrp", category: "media" },
  { company: "Barstool Sports", ats: "greenhouse", token: "barstoolsports", category: "media" },
  { company: "BDG", ats: "lever", token: "BDG", category: "media" },
  { company: "BerlinRosen", ats: "greenhouse", token: "berlinrosen", category: "media" },
  { company: "Brainlabs", ats: "greenhouse", token: "brainlabs", category: "media" },
  { company: "Brand Knew", ats: "lever", token: "brandknew", category: "media" },
  { company: "BSE Global", ats: "greenhouse", token: "bseglobal", category: "media" },
  { company: "Business Insider", ats: "greenhouse", token: "insider", category: "media" },
  { company: "CAA", ats: "workday", token: "caa/wd1/Careers", category: "media" },
  { company: "Chicago Public Media", ats: "greenhouse", token: "cpm", category: "media" },
  { company: "Cinemark", ats: "workday", token: "cinemark/wd1/cinemark", category: "media" },
  { company: "Code and Theory", ats: "greenhouse", token: "codeandtheory", category: "media" },
  { company: "Complex", ats: "lever", token: "Complex", category: "media" },
  { company: "Conde Nast", ats: "workday", token: "condenast/wd115/CondeCareers", category: "media" },
  { company: "Current Global", ats: "greenhouse", token: "currentglobal", category: "media" },
  { company: "Dentsu", ats: "workday", token: "dentsuaegis/wd3/DAN_GLOBAL", category: "media" },
  { company: "DEPT", ats: "greenhouse", token: "dept", category: "media" },
  { company: "Descript", ats: "greenhouse", token: "descript", category: "media" },
  { company: "Detroit Lions", ats: "greenhouse", token: "detroitlions", category: "media" },
  { company: "Digital Extremes", ats: "greenhouse", token: "digitalextremes", category: "media" },
  { company: "Digital Media Management", ats: "lever", token: "digitalmediamanagement", category: "media" },
  { company: "Dude Perfect", ats: "greenhouse", token: "dudeperfect", category: "media" },
  { company: "E.W. Scripps", ats: "workday", token: "scripps/wd115/Scripps_Careers", category: "media" },
  { company: "ElevenLabs", ats: "ashby", token: "elevenlabs", category: "media" },
  { company: "EMARKETER", ats: "greenhouse", token: "emarketer", category: "media" },
  { company: "Endeavor / WME IMG", ats: "workday", token: "wmeimg/wd1/WMEGRP", category: "media" },
  { company: "Epidemic Sound", ats: "ashby", token: "epidemic-sound", category: "media" },
  { company: "Excel Sports Management", ats: "greenhouse", token: "excelsportsmanagement", category: "media" },
  { company: "Fandom", ats: "greenhouse", token: "fandom", category: "media" },
  { company: "FanDuel", ats: "greenhouse", token: "fanduel", category: "media" },
  { company: "Firesprite", ats: "greenhouse", token: "firesprite", category: "media" },
  { company: "First We Feast", ats: "greenhouse", token: "firstwefeast", category: "media" },
  { company: "FleishmanHillard", ats: "greenhouse", token: "fleishmanhillard", category: "media" },
  { company: "Forbes", ats: "greenhouse", token: "forbes", category: "media" },
  { company: "Fubo", ats: "greenhouse", token: "fubotv", category: "media" },
  { company: "GALE", ats: "lever", token: "galepartners", category: "media" },
  { company: "Gameloft", ats: "smartrecruiters", token: "Gameloft", category: "media" },
  { company: "Gamma", ats: "ashby", token: "gamma", category: "media" },
  { company: "Genius", ats: "greenhouse", token: "genius", category: "media" },
  { company: "Getty Images", ats: "lever", token: "gettyimages", category: "media" },
  { company: "GMR Marketing", ats: "greenhouse", token: "gmrmarketing", category: "media" },
  { company: "Goodby Silverstein & Partners", ats: "greenhouse", token: "goodbysilversteinpartners", category: "media" },
  { company: "Goodway Group", ats: "greenhouse", token: "goodwaygroup", category: "media" },
  { company: "Grey", ats: "greenhouse", token: "grey", category: "media" },
  { company: "HeyGen", ats: "greenhouse", token: "heygen", category: "media" },
  { company: "Hovercraft", ats: "greenhouse", token: "hovercraft", category: "media" },
  { company: "Hudl", ats: "greenhouse", token: "hudl", category: "media" },
  { company: "Huge", ats: "greenhouse", token: "hugeinc", category: "media" },
  { company: "HUSH", ats: "lever", token: "hush", category: "media" },
  { company: "Hypebeast", ats: "lever", token: "hypebeast", category: "media" },
  { company: "IDEO", ats: "greenhouse", token: "ideo", category: "media" },
  { company: "Instrument", ats: "lever", token: "instrument", category: "media" },
  { company: "Interbrand", ats: "greenhouse", token: "interbrand", category: "media" },
  { company: "Jack Morton Worldwide", ats: "greenhouse", token: "jackmortonworldwide", category: "media" },
  { company: "Jomboy Media", ats: "greenhouse", token: "jomboymedia", category: "media" },
  { company: "Kepler", ats: "greenhouse", token: "keplergroup", category: "media" },
  { company: "Kettle", ats: "greenhouse", token: "kettle", category: "media" },
  { company: "King", ats: "phenom", token: "careers.king.com", category: "media" },
  { company: "Kit", ats: "ashby", token: "kit", category: "media" },
  { company: "Known", ats: "greenhouse", token: "known", category: "media" },
  { company: "LA Clippers", ats: "greenhouse", token: "laclippers", category: "media" },
  { company: "LAIKA", ats: "greenhouse", token: "laika", category: "media" },
  { company: "Landor", ats: "greenhouse", token: "landor", category: "media" },
  { company: "Low Battery", ats: "lever", token: "raptv", category: "media" },
  { company: "Luma AI", ats: "ashby", token: "lumaai", category: "media" },
  { company: "M Booth", ats: "greenhouse", token: "mbooth", category: "media" },
  { company: "Magnopus", ats: "lever", token: "magnopus", category: "media" },
  { company: "MasterClass", ats: "greenhouse", token: "masterclass", category: "media" },
  { company: "MATTE Projects", ats: "greenhouse", token: "matteprojects", category: "media" },
  { company: "Medal / General Intuition", ats: "ashby", token: "generalintuition-medal", category: "media" },
  { company: "Medium", ats: "greenhouse", token: "medium", category: "media" },
  { company: "Method Communications", ats: "greenhouse", token: "methodcommunications", category: "media" },
  { company: "MLB", ats: "greenhouse", token: "majorleaguebaseball", category: "media" },
  { company: "MLB Network", ats: "greenhouse", token: "mlbnetwork", category: "media" },
  { company: "Momentum Worldwide", ats: "greenhouse", token: "momentumww", category: "media" },
  { company: "Monks", ats: "greenhouse", token: "monks", category: "media" },
  { company: "Monumental Sports", ats: "greenhouse", token: "monumentalsports", category: "media" },
  { company: "Movers+Shakers", ats: "greenhouse", token: "moversshakers", category: "media" },
  { company: "Mux", ats: "ashby", token: "mux", category: "media" },
  { company: "NASCAR", ats: "workday", token: "nascar/wd1/NASCAR", category: "media" },
  { company: "Naughty Dog", ats: "greenhouse", token: "naughtydog", category: "media" },
  { company: "Nen Creative", ats: "ashby", token: "nen-creative", category: "media" },
  { company: "New Engen", ats: "greenhouse", token: "newengeninc", category: "media" },
  { company: "Newsweek", ats: "greenhouse", token: "newsweek", category: "media" },
  { company: "Nexstar Media", ats: "workday", token: "nexstar/wd5/nexstar", category: "media" },
  { company: "NFL", ats: "greenhouse", token: "nflcareers", category: "media" },
  { company: "NPR", ats: "greenhouse", token: "nationalpublicradioinc", category: "media" },
  { company: "OLIVER", ats: "greenhouse", token: "oliver", category: "media" },
  { company: "OLIVER Agency", ats: "greenhouse", token: "oliverusa", category: "media" },
  { company: "OpusClip", ats: "ashby", token: "opusclip", category: "media" },
  { company: "Orchestra", ats: "greenhouse", token: "orchestra", category: "media" },
  { company: "Penske Media", ats: "greenhouse", token: "pmc", category: "media" },
  { company: "Philadelphia Eagles", ats: "greenhouse", token: "philadelphiaeagles", category: "media" },
  { company: "Philo", ats: "greenhouse", token: "philo", category: "media" },
  { company: "Photoroom", ats: "ashby", token: "photoroom", category: "media" },
  { company: "Playfly Sports", ats: "greenhouse", token: "playsports", category: "media" },
  { company: "PlayStation Studios Japan (SIEI)", ats: "greenhouse", token: "siei", category: "media" },
  { company: "PMG", ats: "greenhouse", token: "pmg", category: "media" },
  { company: "Power Digital", ats: "greenhouse", token: "powerdigitalmarketing", category: "media" },
  { company: "PrizePicks", ats: "greenhouse", token: "prizepicks", category: "media" },
  { company: "Prophet", ats: "greenhouse", token: "prophet", category: "media" },
  { company: "RAPP", ats: "greenhouse", token: "rapp", category: "media" },
  { company: "RCX Sports", ats: "greenhouse", token: "rcxsports", category: "media" },
  { company: "Real Chemistry", ats: "greenhouse", token: "realchemistry", category: "media" },
  { company: "Ripples Edge Media", ats: "smartrecruiters", token: "RipplesEdgeMedia", category: "media" },
  { company: "Roc Nation", ats: "workday", token: "livenation/wd503/RNExternalSite", category: "media" },
  { company: "Roku", ats: "greenhouse", token: "roku", category: "media" },
  { company: "Rumble", ats: "greenhouse", token: "rumble", category: "media" },
  { company: "Runway", ats: "ashby", token: "runway-ml", category: "media" },
  { company: "SALT XC", ats: "greenhouse", token: "saltxc", category: "media" },
  { company: "Saylor", ats: "greenhouse", token: "saylor", category: "media" },
  { company: "Scholastic", ats: "workday", token: "scholastic/wd5/External", category: "media" },
  { company: "Scorpion Studios", ats: "greenhouse", token: "scorpionenterprisesllc", category: "media" },
  { company: "Second Dinner", ats: "ashby", token: "seconddinner", category: "media" },
  { company: "Seer Interactive", ats: "lever", token: "seerinteractive", category: "media" },
  { company: "Semafor", ats: "greenhouse", token: "semafor", category: "media" },
  { company: "Shadow", ats: "greenhouse", token: "shadow", category: "media" },
  { company: "Shutterstock", ats: "workday", token: "shutterstock/wd1/ShutterstockCareers", category: "media" },
  { company: "Sid Lee", ats: "greenhouse", token: "sidlee", category: "media" },
  { company: "Sleeper", ats: "ashby", token: "sleeper", category: "media" },
  { company: "Sony Interactive Entertainment", ats: "greenhouse", token: "sonyinteractiveentertainmentglobal", category: "media" },
  { company: "Sphere Entertainment", ats: "greenhouse", token: "sphereentertainment", category: "media" },
  { company: "Splice", ats: "greenhouse", token: "splice", category: "media" },
  { company: "Storyblocks", ats: "greenhouse", token: "storyblocks", category: "media" },
  { company: "Suno", ats: "ashby", token: "suno", category: "media" },
  { company: "Superside", ats: "lever", token: "superside", category: "media" },
  { company: "Synthesia", ats: "ashby", token: "synthesia", category: "media" },
  { company: "TelevisaUnivision", ats: "workday", token: "univision/wd1/External", category: "media" },
  { company: "The Atlantic", ats: "workday", token: "atlanticmedia/wd1/Careers", category: "media" },
  { company: "Thinkingbox", ats: "lever", token: "thinkingbox", category: "media" },
  { company: "Thomson Reuters", ats: "workday", token: "thomsonreuters/wd5/External_Career_Site", category: "media" },
  { company: "Tinuiti", ats: "workday", token: "tinuiti/wd12/Tinuiti", category: "media" },
  { company: "TKO Group", ats: "workday", token: "wwecorp/wd5/TKO", category: "media" },
  { company: "Tripledot Studios", ats: "greenhouse", token: "tripledotstudios", category: "media" },
  { company: "Tubi", ats: "greenhouse", token: "tubitv", category: "media" },
  { company: "Underdog", ats: "greenhouse", token: "underdog", category: "media" },
  { company: "United Talent Agency", ats: "ashby", token: "united-talent-agency", category: "media" },
  { company: "UnitedMasters / Translation", ats: "greenhouse", token: "unitedmasterstranslation", category: "media" },
  { company: "Versant", ats: "smartrecruiters", token: "Versant3", category: "media" },
  { company: "VIZ Media", ats: "greenhouse", token: "vizmedia", category: "media" },
  { company: "Wasserman", ats: "workday", token: "teamwass/wd5/wassermancareers", category: "media" },
  { company: "Wattpad / WEBTOON", ats: "lever", token: "wattpad", category: "media" },
  { company: "Wild Card Creative Group", ats: "greenhouse", token: "wildcardcreativegroup", category: "media" },
  { company: "Wiley", ats: "workday", token: "wiley/wd1/wiley_careers", category: "media" },
  { company: "Wistia", ats: "ashby", token: "wistia", category: "media" },
  { company: "WITHIN", ats: "greenhouse", token: "agencywithin", category: "media" },
  { company: "Wpromote", ats: "lever", token: "wpromote", category: "media" },
  { company: "Zambezi", ats: "lever", token: "zambezi", category: "media" },
  { company: "Zwift", ats: "greenhouse", token: "zwift", category: "media" },
  { company: "Abridge", ats: "ashby", token: "abridge", category: "product" },
  { company: "Adyen", ats: "greenhouse", token: "adyen", category: "product" },
  { company: "Affirm", ats: "greenhouse", token: "affirm", category: "product" },
  { company: "Amplitude", ats: "greenhouse", token: "amplitude", category: "product" },
  { company: "Applied Intuition", ats: "ashby", token: "applied", category: "product" },
  { company: "Ashby", ats: "ashby", token: "ashby", category: "product" },
  { company: "Autodesk", ats: "workday", token: "autodesk/wd1/uni", category: "product" },
  { company: "Baseten", ats: "ashby", token: "baseten", category: "product" },
  { company: "Betterment", ats: "greenhouse", token: "betterment", category: "product" },
  { company: "BILL", ats: "greenhouse", token: "billcom", category: "product" },
  { company: "Calendly", ats: "greenhouse", token: "calendly", category: "product" },
  { company: "Carta", ats: "greenhouse", token: "carta", category: "product" },
  { company: "Catapult Sports", ats: "greenhouse", token: "catapultsports", category: "product" },
  { company: "Cerebras", ats: "ashby", token: "cerebras", category: "product" },
  { company: "Character.AI", ats: "ashby", token: "character", category: "product" },
  { company: "Checkr", ats: "greenhouse", token: "checkr", category: "product" },
  { company: "Chime", ats: "greenhouse", token: "chime", category: "product" },
  { company: "Circle", ats: "ashby", token: "circle", category: "product" },
  { company: "Clay", ats: "ashby", token: "claylabs", category: "product" },
  { company: "Cognition", ats: "ashby", token: "cognition", category: "product" },
  { company: "Cohere", ats: "ashby", token: "cohere", category: "product" },
  { company: "Consensys", ats: "greenhouse", token: "consensys", category: "product" },
  { company: "CoreWeave", ats: "greenhouse", token: "coreweave", category: "product" },
  { company: "Coursera", ats: "greenhouse", token: "coursera", category: "product" },
  { company: "Cresta", ats: "greenhouse", token: "cresta", category: "product" },
  { company: "Culture Amp", ats: "greenhouse", token: "cultureamp", category: "product" },
  { company: "Cursor", ats: "ashby", token: "cursor", category: "product" },
  { company: "Decagon", ats: "ashby", token: "decagon", category: "product" },
  { company: "DoorDash", ats: "greenhouse", token: "doordashusa", category: "product" },
  { company: "eBay", ats: "workday", token: "ebay/wd5/apply", category: "product" },
  { company: "Elastic", ats: "greenhouse", token: "elastic", category: "product" },
  { company: "Expedia", ats: "workday", token: "expedia/wd108/search", category: "product" },
  { company: "Faire", ats: "greenhouse", token: "faire", category: "product" },
  { company: "Fivetran", ats: "greenhouse", token: "fivetran", category: "product" },
  { company: "Front", ats: "ashby", token: "frontcareers", category: "product" },
  { company: "Gemini", ats: "greenhouse", token: "gemini", category: "product" },
  { company: "GitLab", ats: "greenhouse", token: "gitlab", category: "product" },
  { company: "Glean", ats: "greenhouse", token: "gleanwork", category: "product" },
  { company: "GoDaddy", ats: "greenhouse", token: "godaddy", category: "product" },
  { company: "Gorgias", ats: "ashby", token: "gorgias", category: "product" },
  { company: "Greenhouse", ats: "greenhouse", token: "greenhouse", category: "product" },
  { company: "Gusto", ats: "greenhouse", token: "gusto", category: "product" },
  { company: "Harvey", ats: "ashby", token: "harvey", category: "product" },
  { company: "HP", ats: "workday", token: "hp/wd5/ExternalCareerSite", category: "product" },
  { company: "HubSpot", ats: "greenhouse", token: "hubspotjobs", category: "product" },
  { company: "Instabase", ats: "greenhouse", token: "instabase", category: "product" },
  { company: "Intercom", ats: "greenhouse", token: "intercom", category: "product" },
  { company: "Ironclad", ats: "ashby", token: "ironcladhq", category: "product" },
  { company: "Iterable", ats: "greenhouse", token: "iterable", category: "product" },
  { company: "Kalshi", ats: "ashby", token: "kalshi", category: "product" },
  { company: "Khan Academy", ats: "greenhouse", token: "khanacademy", category: "product" },
  { company: "Kraken", ats: "ashby", token: "kraken.com", category: "product" },
  { company: "Lambda", ats: "ashby", token: "lambda", category: "product" },
  { company: "LangChain", ats: "ashby", token: "langchain", category: "product" },
  { company: "Lattice", ats: "greenhouse", token: "lattice", category: "product" },
  { company: "LaunchDarkly", ats: "greenhouse", token: "launchdarkly", category: "product" },
  { company: "Life360", ats: "greenhouse", token: "life360", category: "product" },
  { company: "Mercor", ats: "ashby", token: "mercor", category: "product" },
  { company: "Mercury", ats: "greenhouse", token: "mercury", category: "product" },
  { company: "Mixpanel", ats: "greenhouse", token: "mixpanel", category: "product" },
  { company: "Modal", ats: "ashby", token: "modal", category: "product" },
  { company: "MongoDB", ats: "greenhouse", token: "mongodb", category: "product" },
  { company: "Motive", ats: "greenhouse", token: "gomotive", category: "product" },
  { company: "Nextdoor", ats: "greenhouse", token: "nextdoor", category: "product" },
  { company: "PagerDuty", ats: "greenhouse", token: "pagerduty", category: "product" },
  { company: "Palantir", ats: "lever", token: "palantir", category: "product" },
  { company: "Perplexity", ats: "ashby", token: "perplexity", category: "product" },
  { company: "Pinecone", ats: "ashby", token: "pinecone", category: "product" },
  { company: "Polymarket", ats: "ashby", token: "polymarket", category: "product" },
  { company: "Postman", ats: "greenhouse", token: "postman", category: "product" },
  { company: "Qualtrics", ats: "greenhouse", token: "qualtrics", category: "product" },
  { company: "Replit", ats: "ashby", token: "replit", category: "product" },
  { company: "Ritual", ats: "greenhouse", token: "ritual", category: "product" },
  { company: "Samsara", ats: "greenhouse", token: "samsara", category: "product" },
  { company: "SeatGeek", ats: "greenhouse", token: "seatgeek", category: "product" },
  { company: "Sierra", ats: "ashby", token: "sierra", category: "product" },
  { company: "Similarweb", ats: "greenhouse", token: "similarweb", category: "product" },
  { company: "Smartsheet", ats: "greenhouse", token: "smartsheet", category: "product" },
  { company: "SoFi", ats: "greenhouse", token: "sofi", category: "product" },
  { company: "Sourcegraph", ats: "greenhouse", token: "sourcegraph91", category: "product" },
  { company: "Strava", ats: "ashby", token: "strava", category: "product" },
  { company: "StubHub", ats: "greenhouse", token: "stubhubinc", category: "product" },
  { company: "Supabase", ats: "ashby", token: "supabase", category: "product" },
  { company: "Toast", ats: "greenhouse", token: "toast", category: "product" },
  { company: "Together AI", ats: "greenhouse", token: "togetherai", category: "product" },
  { company: "Trustpilot", ats: "greenhouse", token: "trustpilot", category: "product" },
  { company: "Typeform", ats: "greenhouse", token: "typeform", category: "product" },
  { company: "Udemy", ats: "greenhouse", token: "udemy", category: "product" },
  { company: "Vanta", ats: "ashby", token: "vanta", category: "product" },
  { company: "Verkada", ats: "greenhouse", token: "verkada", category: "product" },
  { company: "Waymo", ats: "greenhouse", token: "waymo", category: "product" },
  { company: "Webflow", ats: "greenhouse", token: "webflow", category: "product" },
  { company: "Wheelhouse", ats: "greenhouse", token: "wheelhouse", category: "product" },
  { company: "Wise", ats: "smartrecruiters", token: "Wise", category: "product" },
  { company: "Writer", ats: "ashby", token: "writer", category: "product" },
  { company: "Yotpo", ats: "greenhouse", token: "yotpo", category: "product" },
  { company: "Zapier", ats: "ashby", token: "zapier", category: "product" },
  // Round four: more Chicago, plus a community dataset that reaches the
  // giants whose own APIs refuse anything without a browser.
  { company: "Alight", ats: "smartrecruiters", token: "alight", category: "local" },
  { company: "Amount", ats: "greenhouse", token: "amount", category: "local" },
  { company: "BMO", ats: "workday", token: "bmo/wd3/External", category: "local" },
  { company: "Belvedere", ats: "lever", token: "belvederetrading", category: "local" },
  { company: "Beyond Finance", ats: "greenhouse", token: "beyondfinance", category: "local" },
  { company: "Blue Owl", ats: "workday", token: "blueowl/wd1/blueowl", category: "local" },
  { company: "ComEd", ats: "radancy", token: "careers.comed.com", category: "local" },
  { company: "Cresco Labs", ats: "greenhouse", token: "crescolabs", category: "local" },
  { company: "Echo Global", ats: "greenhouse", token: "echo", category: "local" },
  { company: "HCSC", ats: "workday", token: "hcsc/wd1/hcsc_External", category: "local" },
  { company: "JLL", ats: "workday", token: "jll/wd1/jllcareers", category: "local" },
  { company: "Jump Trading", ats: "greenhouse", token: "jumptrading", category: "local" },
  { company: "M1 Finance", ats: "smartrecruiters", token: "m1finance", category: "local" },
  { company: "Northwestern Mutual", ats: "smartrecruiters", token: "northwesternmutual", category: "local" },
  { company: "Simplify (Product, S27)", ats: "simplify", token: "summer2027", category: "product" },
  { company: "SpotHero", ats: "greenhouse", token: "spothero", category: "local" },
  { company: "Sysco", ats: "workday", token: "sysco/wd5/syscocareers", category: "local" },
  { company: "Tovala", ats: "lever", token: "tovala", category: "local" },
  { company: "TransUnion", ats: "workday", token: "transunion/wd5/transunion", category: "local" },
  { company: "US Foods", ats: "phenom", token: "careers.usfoods.com", category: "local" },
  { company: "VSA Partners", ats: "greenhouse", token: "vsapartners", category: "media" },

  // Round three: the moonshots, the studios, the boutique Chicago shops and
  // the sports/production names. Every token probed live before landing here.
  { company: "A24", ats: "greenhouse", token: "a24", category: "media" },
  { company: "ActiveCampaign", ats: "lever", token: "activecampaign", category: "local" },
  { company: "Amazon", ats: "amazon", token: "amazon", category: "product" },
  { company: "Aon", ats: "radancy", token: "jobs.aon.com", category: "local" },
  { company: "Blizzard", ats: "phenom", token: "careers.blizzard.com", category: "media" },
  { company: "Block", ats: "greenhouse", token: "block", category: "product" },
  { company: "Bombas", ats: "greenhouse", token: "bombas", category: "media" },
  { company: "Booking", ats: "radancy", token: "jobs.booking.com", category: "product" },
  { company: "Bungie", ats: "greenhouse", token: "bungie", category: "media" },
  { company: "Cisco", ats: "workday", token: "cisco/wd5/cisco_careers", category: "product" },
  { company: "Crunchyroll", ats: "greenhouse", token: "crunchyroll", category: "media" },
  { company: "Dropbox", ats: "greenhouse", token: "dropbox", category: "product" },
  { company: "Etsy", ats: "workday", token: "etsy/wd5/etsy_careers", category: "product" },
  { company: "G2", ats: "ashby", token: "g2", category: "local" },
  { company: "Gearbox", ats: "greenhouse", token: "gearbox", category: "media" },
  { company: "ITW", ats: "phenom", token: "careers.itw.com", category: "local" },
  { company: "Illumination", ats: "lever", token: "illumination", category: "media" },
  { company: "Intel", ats: "workday", token: "intel/wd1/External", category: "product" },
  { company: "Jam City", ats: "lever", token: "jamcity", category: "media" },
  { company: "Jellyfish", ats: "ashby", token: "jellyfish", category: "media" },
  { company: "Kin Insurance", ats: "ashby", token: "kin", category: "local" },
  { company: "Krafton", ats: "greenhouse", token: "krafton", category: "media" },
  { company: "Learfield", ats: "workday", token: "learfield/wd5/learfield", category: "media" },
  { company: "LinkedIn", ats: "greenhouse", token: "linkedin", category: "product" },
  { company: "Liquid Death", ats: "greenhouse", token: "liquiddeath", category: "media" },
  { company: "Litera", ats: "workday", token: "litera/wd12/litera_careers", category: "local" },
  { company: "Lucid", ats: "greenhouse", token: "lucidmotors", category: "local" },
  { company: "NBA", ats: "phenom", token: "careers.nba.com", category: "media" },
  { company: "NVIDIA", ats: "workday", token: "nvidia/wd5/NVIDIAExternalCareerSite", category: "product" },
  { company: "Navistar", ats: "radancy", token: "careers.navistar.com", category: "local" },
  { company: "Neon", ats: "lever", token: "neon", category: "media" },
  { company: "New Balance", ats: "workday", token: "newbalance/wd1/Careers", category: "media" },
  { company: "Octagon", ats: "greenhouse", token: "octagon", category: "media" },
  { company: "Okta", ats: "greenhouse", token: "okta", category: "product" },
  { company: "Olipop", ats: "greenhouse", token: "olipop", category: "media" },
  { company: "Polaris", ats: "greenhouse", token: "polaris", category: "local" },
  { company: "Project44", ats: "greenhouse", token: "project44", category: "local" },
  { company: "Schafer Condon Carter", ats: "smartrecruiters", token: "schafercondoncarter", category: "media" },
  { company: "Scopely", ats: "greenhouse", token: "scopely", category: "media" },
  { company: "ServiceNow", ats: "smartrecruiters", token: "servicenow", category: "product" },
  { company: "Skydance", ats: "lever", token: "skydance", category: "media" },
  { company: "Snowflake", ats: "ashby", token: "snowflake", category: "product" },
  { company: "Starz", ats: "workday", token: "starz/wd5/starz", category: "media" },
  { company: "Teamworks", ats: "ashby", token: "teamworks", category: "media" },
  { company: "TripAdvisor", ats: "greenhouse", token: "tripadvisor", category: "product" },
  { company: "Twilio", ats: "greenhouse", token: "twilio", category: "product" },
  { company: "Uber", ats: "smartrecruiters", token: "uber", category: "product" },
  { company: "Vuori", ats: "greenhouse", token: "vuori", category: "media" },
  { company: "Workday", ats: "workday", token: "workday/wd5/workday", category: "product" },
  { company: "Xsolla", ats: "lever", token: "xsolla", category: "media" },
  { company: "Zeno Group", ats: "ashby", token: "zeno", category: "media" },
  { company: "Zoom", ats: "workday", token: "zoom/wd5/zoom", category: "product" },

  // The holdouts, recovered by following each careers URL until it admitted
  // what it runs on rather than by guessing slugs. Two of these matter most:
  // Rivian builds in Normal and State Farm is headquartered in Bloomington —
  // both a short drive from campus.
  { company: "Rivian", ats: "radancy", token: "careers.rivian.com", category: "local" },
  { company: "State Farm", ats: "radancy", token: "jobs.statefarm.com", category: "local" },
  { company: "United Airlines", ats: "phenom", token: "careers.united.com", category: "local" },
  { company: "Conagra Brands", ats: "phenom", token: "careers.conagrabrands.com", category: "local" },
  { company: "Northern Trust", ats: "workday", token: "ntrs/wd1/northerntrust", category: "local" },
  { company: "Discover / Capital One", ats: "workday", token: "capitalone/wd12/Capital_One", category: "local" },
  { company: "Nike", ats: "workday", token: "nike/wd1/nke", category: "brand" },

  // Round two of the watchlist, weighted to Illinois — the owner is at Illinois
  // State, and a summer within driving distance is this year's plan. Every
  // token below was probed live before it was written down.
  { company: "AbbVie", ats: "smartrecruiters", token: "abbvie", category: "local" },
  { company: "Abbott", ats: "workday", token: "abbott/wd5/abbottcareers", category: "local" },
  { company: "Allstate", ats: "workday", token: "allstate/wd5/allstate_careers", category: "local" },
  { company: "Beam Suntory", ats: "smartrecruiters", token: "beamsuntory", category: "brand" },
  { company: "Braze", ats: "greenhouse", token: "braze", category: "local" },
  { company: "CDW", ats: "workday", token: "cdw/wd5/Careers", category: "local" },
  { company: "Cameo", ats: "greenhouse", token: "cameo", category: "media" },
  { company: "Cars.com", ats: "workday", token: "cars/wd12/cars", category: "local" },
  { company: "Chewy", ats: "workday", token: "chewy/wd5/External", category: "brand" },
  { company: "Clorox", ats: "workday", token: "clorox/wd1/clorox", category: "brand" },
  { company: "Comscore", ats: "workday", token: "comscore/wd5/External", category: "media" },
  { company: "DraftKings", ats: "workday", token: "draftkings/wd1/draftkings", category: "media" },
  { company: "Enova", ats: "greenhouse", token: "enova", category: "local" },
  { company: "Fanatics", ats: "greenhouse", token: "fanaticsinc", category: "media" },
  { company: "Gap", ats: "smartrecruiters", token: "gapinc", category: "brand" },
  { company: "Genius Sports", ats: "greenhouse", token: "geniussports", category: "media" },
  { company: "Golin", ats: "greenhouse", token: "golin", category: "media" },
  { company: "Groupon", ats: "greenhouse", token: "groupon", category: "local" },
  { company: "Hasbro", ats: "greenhouse", token: "hasbro", category: "brand" },
  { company: "Highdive", ats: "greenhouse", token: "highdive", category: "media" },
  { company: "Huron", ats: "workday", token: "huron/wd1/huroncareers", category: "business" },
  { company: "Kimberly-Clark", ats: "smartrecruiters", token: "kimberlyclark", category: "brand" },
  { company: "Live Nation", ats: "smartrecruiters", token: "livenationentertainment", category: "media" },
  { company: "McDonalds", ats: "smartrecruiters", token: "mcdonaldscorporation", category: "local" },
  { company: "Mondelez", ats: "workday", token: "mdlz/wd3/External", category: "local" },
  { company: "Morningstar", ats: "workday", token: "morningstar/wd5/morningstar", category: "local" },
  { company: "Motorola Solutions", ats: "workday", token: "motorolasolutions/wd5/Careers", category: "local" },
  { company: "On Running", ats: "greenhouse", token: "onrunning", category: "brand" },
  { company: "Peacock / Sky", ats: "workday", token: "sky/wd3/sky_careers", category: "media" },
  { company: "Relativity", ats: "greenhouse", token: "relativity", category: "local" },
  { company: "Sportradar", ats: "smartrecruiters", token: "sportradar", category: "media" },
  { company: "Tempus", ats: "workday", token: "tempus/wd5/tempus_careers", category: "local" },
  { company: "The New York Times", ats: "greenhouse", token: "thenewyorktimes", category: "media" },
  { company: "Universal Music", ats: "smartrecruiters", token: "universalmusicgroup", category: "media" },
  { company: "VML", ats: "greenhouse", token: "wundermanthompson", category: "media" },
  { company: "Warner Music", ats: "lever", token: "wmg", category: "media" },
  { company: "Wayfair", ats: "smartrecruiters", token: "wayfair", category: "brand" },
  { company: "iHeartMedia", ats: "smartrecruiters", token: "iheartmedia", category: "media" },

  // Workday, where the biggest names live. `token` is "tenant/dc/site"; each
  // was probed live and returns a real board. These carry the roles most worth
  // catching — Disney, NBCU (through Comcast's tenant), Warner Bros Discovery.
  { company: "Disney", ats: "workday", token: "disney/wd5/disneycareer", category: "media" },
  { company: "NBCUniversal / Comcast", ats: "workday", token: "comcast/wd5/Comcast_Careers", category: "media" },
  { company: "Warner Bros Discovery", ats: "workday", token: "warnerbros/wd5/global", category: "media" },
  { company: "Target", ats: "workday", token: "target/wd5/targetcareers", category: "brand" },
  { company: "Salesforce", ats: "workday", token: "salesforce/wd12/External_Career_Site", category: "product" },
  { company: "Adobe", ats: "workday", token: "adobe/wd5/external_experienced", category: "product" },

  { company: "Away", ats: "ashby", token: "away", category: "brand" },
  { company: "Glossier", ats: "greenhouse", token: "glossier", category: "brand" },
  { company: "Peloton", ats: "greenhouse", token: "peloton", category: "brand" },
  { company: "Sweetgreen", ats: "greenhouse", token: "sweetgreen", category: "brand" },
  { company: "Attentive", ats: "greenhouse", token: "attentive", category: "media" },
  { company: "Axios", ats: "greenhouse", token: "axios", category: "media" },
  { company: "BuzzFeed", ats: "greenhouse", token: "buzzfeed", category: "media" },
  { company: "Critical Mass", ats: "greenhouse", token: "criticalmass", category: "media" },
  { company: "Discord", ats: "greenhouse", token: "discord", category: "media" },
  { company: "Epic Games", ats: "greenhouse", token: "epicgames", category: "media" },
  { company: "GroupM", ats: "greenhouse", token: "wpp", category: "media" },
  { company: "Hearst", ats: "greenhouse", token: "hearst", category: "media" },
  { company: "Later", ats: "greenhouse", token: "later", category: "media" },
  { company: "Mediabrands", ats: "greenhouse", token: "mediabrands", category: "media" },
  { company: "Morning Brew", ats: "lever", token: "morningbrew", category: "media" },
  { company: "Ogilvy", ats: "greenhouse", token: "ogilvy", category: "media" },
  { company: "Omnicom", ats: "smartrecruiters", token: "omnicomgroup", category: "media" },
  { company: "Patreon", ats: "ashby", token: "patreon", category: "media" },
  { company: "R/GA", ats: "greenhouse", token: "rga", category: "media" },
  { company: "Riot Games", ats: "greenhouse", token: "riotgames", category: "media" },
  { company: "Roblox", ats: "greenhouse", token: "roblox", category: "media" },
  { company: "Spotify", ats: "lever", token: "spotify", category: "media" },
  { company: "Substack", ats: "ashby", token: "substack", category: "media" },
  { company: "Take Two", ats: "greenhouse", token: "taketwo", category: "media" },
  { company: "The Athletic", ats: "lever", token: "theathletic", category: "media" },
  { company: "Twitch", ats: "greenhouse", token: "twitch", category: "media" },
  { company: "Vayner Media", ats: "greenhouse", token: "vaynermedia", category: "media" },
  { company: "Vox Media", ats: "greenhouse", token: "voxmedia", category: "media" },
  { company: "Weber Shandwick", ats: "greenhouse", token: "webershandwick", category: "media" },
  { company: "Wieden Kennedy", ats: "greenhouse", token: "wk", category: "media" },
  { company: "Zeta Global", ats: "greenhouse", token: "zetaglobal", category: "media" },
  { company: "Airbnb", ats: "greenhouse", token: "airbnb", category: "product" },
  { company: "Airtable", ats: "greenhouse", token: "airtable", category: "product" },
  { company: "Anthropic", ats: "greenhouse", token: "anthropic", category: "product" },
  { company: "Asana", ats: "greenhouse", token: "asana", category: "product" },
  { company: "Brex", ats: "greenhouse", token: "brex", category: "product" },
  { company: "Cloudflare", ats: "greenhouse", token: "cloudflare", category: "product" },
  { company: "Coinbase", ats: "greenhouse", token: "coinbase", category: "product" },
  { company: "Databricks", ats: "greenhouse", token: "databricks", category: "product" },
  { company: "Datadog", ats: "greenhouse", token: "datadog", category: "product" },
  { company: "Duolingo", ats: "greenhouse", token: "duolingo", category: "product" },
  { company: "Figma", ats: "greenhouse", token: "figma", category: "product" },
  { company: "Hootsuite", ats: "greenhouse", token: "hootsuite", category: "product" },
  { company: "Instacart", ats: "greenhouse", token: "instacart", category: "product" },
  { company: "Klaviyo", ats: "greenhouse", token: "klaviyo", category: "product" },
  { company: "Linear", ats: "ashby", token: "linear", category: "product" },
  { company: "Lyft", ats: "greenhouse", token: "lyft", category: "product" },
  { company: "Notion", ats: "ashby", token: "notion", category: "product" },
  { company: "OpenAI", ats: "ashby", token: "openai", category: "product" },
  { company: "Pinterest", ats: "greenhouse", token: "pinterest", category: "product" },
  { company: "Plaid", ats: "ashby", token: "plaid", category: "product" },
  { company: "Ramp", ats: "ashby", token: "ramp", category: "product" },
  { company: "Reddit", ats: "greenhouse", token: "reddit", category: "product" },
  { company: "Robinhood", ats: "greenhouse", token: "robinhood", category: "product" },
  { company: "Scale AI", ats: "greenhouse", token: "scaleai", category: "product" },
  { company: "Sprout Social", ats: "greenhouse", token: "sproutsocial", category: "product" },
  { company: "Squarespace", ats: "greenhouse", token: "squarespace", category: "product" },
  { company: "Stripe", ats: "greenhouse", token: "stripe", category: "product" },
  { company: "Vercel", ats: "greenhouse", token: "vercel", category: "product" },];


const { data, error } = await supabase
  .from("job_sources")
  .upsert(WATCHLIST, { onConflict: "ats,token", ignoreDuplicates: true })
  .select();

if (error) {
  console.error("SEED FAILED:", error.message);
  process.exit(1);
}

const { count } = await supabase
  .from("job_sources")
  .select("id", { count: "exact", head: true });

console.log(`Watchlist: ${WATCHLIST.length} boards offered, ${count} now stored.`);
